// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectX.Data;

#nullable disable

namespace ProjectX.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("ProjectX.Models.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnersMail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnersName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Passcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Passls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ShipmentStartDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("ShipmentWeight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Shipments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("316a3643-1bd0-4f47-9699-dfd6d5c3acce"),
                            DeliveryDate = new DateTime(2024, 6, 7, 2, 33, 41, 891, DateTimeKind.Local).AddTicks(1397),
                            Destination = "Destination1",
                            ItemName = "Item1",
                            Location = "Location1",
                            OwnersMail = "owner1@example.com",
                            OwnersName = "Owner1",
                            Passcode = "1234",
                            Passls = "pass1",
                            ShipmentStartDate = new DateTime(2024, 5, 28, 2, 33, 41, 891, DateTimeKind.Local).AddTicks(1376),
                            ShipmentWeight = 10.0
                        },
                        new
                        {
                            Id = new Guid("c0a996ae-6405-4026-959f-061738d54113"),
                            DeliveryDate = new DateTime(2024, 6, 4, 2, 33, 41, 891, DateTimeKind.Local).AddTicks(1403),
                            Destination = "Destination2",
                            ItemName = "Item2",
                            Location = "Location2",
                            OwnersMail = "owner2@example.com",
                            OwnersName = "Owner2",
                            Passcode = "5678",
                            Passls = "pass2",
                            ShipmentStartDate = new DateTime(2024, 5, 23, 2, 33, 41, 891, DateTimeKind.Local).AddTicks(1402),
                            ShipmentWeight = 20.0
                        },
                        new
                        {
                            Id = new Guid("7f4cf144-efcf-47bd-9ffc-5cafc97a6864"),
                            DeliveryDate = new DateTime(2024, 6, 9, 2, 33, 41, 891, DateTimeKind.Local).AddTicks(1407),
                            Destination = "Destination3",
                            ItemName = "Item3",
                            Location = "Location3",
                            OwnersMail = "owner3@example.com",
                            OwnersName = "Owner3",
                            Passcode = "abcd",
                            Passls = "pass3",
                            ShipmentStartDate = new DateTime(2024, 5, 26, 2, 33, 41, 891, DateTimeKind.Local).AddTicks(1407),
                            ShipmentWeight = 30.0
                        },
                        new
                        {
                            Id = new Guid("a1929b7b-91eb-4f1d-a8c8-4dffa88db762"),
                            DeliveryDate = new DateTime(2024, 6, 12, 2, 33, 41, 891, DateTimeKind.Local).AddTicks(1412),
                            Destination = "Destination4",
                            ItemName = "Item4",
                            Location = "Location4",
                            OwnersMail = "owner4@example.com",
                            OwnersName = "Owner4",
                            Passcode = "efgh",
                            Passls = "pass4",
                            ShipmentStartDate = new DateTime(2024, 5, 30, 2, 33, 41, 891, DateTimeKind.Local).AddTicks(1411),
                            ShipmentWeight = 40.0
                        });
                });

            modelBuilder.Entity("ProjectX.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAdmin = true,
                            Password = "password1",
                            Username = "admin1"
                        },
                        new
                        {
                            Id = 2,
                            IsAdmin = true,
                            Password = "password2",
                            Username = "admin2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
